apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260615-224627-fi27vzhr08jq-service
spec:
  selector:
    app: enterprise-system-20260615-224627-fi27vzhr08jq
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
